version: '3.8'

services:
  canteen-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
        - postgres


  postgres:
    restart: always
    image: postgres:latest
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=12345
        - POSTGRES_DB=canteen-database
    ports:
        - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: